---
name: Just Lint

on:
  push:
    branches: ["@@defaultBranch@@"]
  pull_request:
    branches: ["@@defaultBranch@@"]

jobs:
  lint:
    runs-on: @@runsOn@@
    steps:
      - uses: actions/checkout@v7
      - name: Install just
        uses: extractions/setup-just@v4
      - name: Fetch justfiles
        run: just fetch
      - name: Lint justfiles
        run: just just-fmt-check
